### ISSUE TITLE
Choose License for qtmp3player

### ISSUE THREAD

**Issue by m33k** [vangourd/qtmp3player#2]
License options to discuss: https://choosealicense.com/licenses/

**Comment by m33k** [comment]
@vangourd do you have any preferences on licensing?

**Comment by vangourd** [comment]
None at all. I think the GPL is the one that prevents commercial use yeah?

**Comment by m33k** [comment]
@vangourd There are different versions of the GPL license, but they do allow commercial use. However, they'd have to disclose any changes they make to the project.

I don't mind if we kept the project open source so anyone in the community could contribute. What do you think? 

As far as licensing goes, I don't see a need to make this complex so MIT license seems good. Anyone can do what they want with the project as long as they keep our names on the project and the license stays the same for their fork and what not. Plus they don't have to let us know if they have made changes to this project. If you want to be notified of any changes by a third party we can opt for the Apache 2 License.

Were you interested in preventing commercial use the project?

**Comment by vangourd** [comment]
Honestly doesn't matter to me. MIT license seems fine.

**Comment by m33k** [comment]
Sounds good. We'll go with MIT license for this project.
