### ISSUE TITLE
Choose Style Guide

### ISSUE THREAD

**Issue by m33k** [vangourd/qtmp3player#7]
@vangourd brought up a good idea about choosing a style guide for the project.

**Comment by m33k** [comment]
I haven't looked into the style guides, but a quick search shows there different ones for each language/lib.

Python: https://www.python.org/dev/peps/pep-0008/
QT Library: https://wiki.qt.io/Qt_Coding_Style
C++: https://google.github.io/styleguide/cppguide.html

**Comment by vangourd** [comment]
I think we've reached a conclusion on this one @m33k. Feel free to re-open if you want to consider it more.
